locallibrary/catalog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from .views import BorrowBookView, BookCreateView, BookUpdateView, BookDeleteView, add_beloved_book

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='book_list'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author_detail'),

    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('my_borrowed/', views.MyBorrowedView.as_view(), name='my_borrowed'),
    path('all_borrowed_books/', views.BorrowedBooksByLibrarianView.as_view(), name='all_borrowed_books'),
    path('book/<uuid:pk>/borrow/', BorrowBookView.as_view(), name='borrow_book'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew_book_librarian'),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
    path('books/create/', BookCreateView.as_view(), name='book_create'),
    path('books/<int:pk>/update/', BookUpdateView.as_view(), name='book_update'),
    path('books/<int:pk>/delete/', BookDeleteView.as_view(), name='book_delete'),
    path('book/<int:pk>/add_beloved/', add_beloved_book, name='add_beloved_book'),
]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

locallibrary/catalog/models.py
import uuid

from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.timezone import now


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        return reverse('author_detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

    @property
    def name(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        pass


class Genre(models.Model):
    name = models.CharField(max_length=100, help_text="Введите жанр книги (например, Научная фантастика, Нон-фикшн)")

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    description = models.TextField(max_length=1000, help_text="Введите краткое описание книги",
                                   default="Описание отсутствует")
    isbn = models.CharField('ISBN', max_length=13)
    genre = models.ManyToManyField('Genre', help_text="Выберите жанр для этой книги")
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title



    def get_absolute_url(self):
        return reverse('book_detail', args=[str(self.id)])


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False,
                          help_text="Уникальный идентификатор для этой конкретной книги во всей библиотеке")
    book = models.ForeignKey('Book', on_delete=models.CASCADE, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    date_borrowed = models.DateField(default=now, help_text="Дата взятия книги")
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    status = models.CharField(
        max_length=1,
        choices=(("m", "Обслуживание"), ("o", "Предоставлено в аренду"), ("a", "Доступно"), ("r", "Зарезервировано")),
        blank=True,
        default='m',
        help_text='Наличие свободных номеров',
    )

    class Meta:
        ordering = ['due_back']
        permissions = [
            ("can_mark_returned", "Set book as returned")
        ]

    def __str__(self):
        return f'{self.id} ({self.book.title})'


class BelovedBook(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="beloved_book")
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        if BelovedBook.objects.filter(user=self.user).exists() and not self.pk:
            raise ValidationError("У вас уже есть любимая книга!")
        super().save(*args, **kwargs)

    def __str__(self):
        return f'Любимая книга {self.user.username}: {self.book.title}'

locallibrary/catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from .models import BookInstance, Book
import datetime


class RenewBookForm(forms.ModelForm):
    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('Дата возврата')}
        help_texts = {'due_back': _('Введите дату в пределах 4 недель от сегодня.')}
        widgets = {
            'due_back': forms.SelectDateWidget(),
        }

    def clean_due_back(self):
        data = self.cleaned_data['due_back']

        if data < datetime.date.today():
            raise ValidationError(_('Неверная дата — она уже прошла.'))

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Неверная дата — больше чем на 4 недели вперед.'))

        return data


class BorrowBookForm(forms.Form):
    due_back = forms.DateField(
        label="Дата возврата",
        widget=forms.SelectDateWidget(),
        initial=datetime.date.today() + datetime.timedelta(weeks=2),
    )

    def clean_due_back(self):
        data = self.cleaned_data['due_back']

        if data < datetime.date.today():
            raise forms.ValidationError('Дата возврата не может быть в прошлом.')

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise forms.ValidationError('Дата возврата не может быть позже, чем через 4 недели.')

        return data


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'description', 'isbn', 'genre']
        labels = {
            'title': 'Название',
            'author': 'Автор',
            'description': 'Описание',
            'isbn': 'ISBN',
            'genre': 'Жанры',
        }
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4}),
            'genre': forms.CheckboxSelectMultiple(),
        }

        def clean_genre(self):
            genres = self.cleaned_data.get('genre')
            if genres and genres.count() > 3:
                raise forms.ValidationError("Вы не можете выбрать больше 3 жанров.")
            return genres

locallibrary/catalog/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.generic import ListView, FormView, CreateView, UpdateView, DeleteView
import datetime
from django.db.models import Q
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from .forms import RenewBookForm, BorrowBookForm, BookForm
from .models import Book, Author, BookInstance, BelovedBook


@login_required
def index(request):
    search_word = request.GET.get('q', '')

    num_books = Book.objects.all().count()
    num_authors = Author.objects.all().count()

    if search_word:
        num_books_with_word = Book.objects.filter(
            Q(title__icontains=search_word) | Q(description__icontains=search_word)
        ).count()
        genres_with_books = Book.objects.filter(
            Q(title__icontains=search_word) | Q(description__icontains=search_word)
        ).values_list('genre', flat=True).distinct()
        num_genres_with_books = genres_with_books.count()
    else:
        num_books_with_word = 0
        num_genres_with_books = 0

    num_visits = request.session.get('num_visits', 0)
    num_visits += 1
    request.session['num_visits'] = num_visits

    context = {
        'num_books': num_books,
        'num_authors': num_authors,
        'num_books_with_word': num_books_with_word,
        'num_genres_with_books': num_genres_with_books,
        'search_word': search_word,
        'num_visits': num_visits,
    }

    return render(request, 'index.html', context=context)


class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    context_object_name = 'book_list'
    template_name = 'book_list.html'
    paginate_by = 5

    def get_queryset(self):
        return Book.objects.all()


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book
    context_object_name = 'book'
    template_name = 'book_detail.html'


class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author
    context_object_name = 'authors'
    template_name = 'authors.html'

    def get_queryset(self):
        return Author.objects.all()


class AuthorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Author
    context_object_name = 'author'
    template_name = 'author_detail.html'


class MyBorrowedView(LoginRequiredMixin, ListView):
    model = BookInstance
    template_name = 'my_borrowed.html'
    context_object_name = 'borrowed_books'

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user, status='o')


class BorrowedBooksByLibrarianView(PermissionRequiredMixin, ListView):
    model = BookInstance
    template_name = 'all_borrowed_books.html'
    context_object_name = 'borrowed_books'
    permission_required = 'catalog.can_mark_returned'

    def get_queryset(self):
        return BookInstance.objects.filter(status='o').order_by('due_back')


class BorrowBookView(LoginRequiredMixin, FormView):
    template_name = 'borrow_book.html'
    form_class = BorrowBookForm

    def form_valid(self, form):
        book_instance_id = self.kwargs['pk']
        book_instance = get_object_or_404(BookInstance, pk=book_instance_id)

        if book_instance.status != 'a':
            form.add_error(None, "Эта книга уже занята.")
            return self.form_invalid(form)

        book_instance.borrower = self.request.user
        book_instance.due_back = form.cleaned_data['due_back']
        book_instance.status = 'o'  # Меняем статус на "взята"
        book_instance.save()

        return redirect('index')


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    if request.method == 'POST':
        form = RenewBookForm(request.POST)

        if form.is_valid():
            book_instance.due_back = form.cleaned_data['due_back']
            book_instance.save()

            return HttpResponseRedirect(reverse('all_borrowed_books'))

    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'book_renew_librarian.html', context)


class AuthorCreate(PermissionRequiredMixin, CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    initial = {'date_of_death': ''}
    permission_required = 'catalog.add_author'
    template_name = 'author_form.html'


class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    template_name = 'author_update.html'
    success_url = reverse_lazy('authors')
    permission_required = 'catalog.change_author'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Обновить сведения об авторе"
        return context


class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    template_name = 'author_delete.html'
    success_url = reverse_lazy('authors')
    permission_required = 'catalog.delete_author'

    def form_valid(self, form):
        try:
            self.object.delete()
            return HttpResponseRedirect(self.success_url)
        except Exception:
            return HttpResponseRedirect(
                reverse("author-delete", kwargs={"pk": self.object.pk})
            )


@method_decorator(permission_required('catalog.add_book'), name='dispatch')
class BookCreateView(CreateView):
    model = Book
    form_class = BookForm
    template_name = 'book_form.html'
    success_url = reverse_lazy('book_list')

    def form_valid(self, form):
        book = form.save(commit=False)
        book.save()
        form.save_m2m()
        messages.success(self.request, f"Книга '{book.title}' успешно создана.")
        return super().form_valid(form)


@method_decorator(permission_required('catalog.change_book'), name='dispatch')
class BookUpdateView(UpdateView):
    model = Book
    form_class = BookForm
    template_name = 'book_form.html'
    success_url = reverse_lazy('book_list')

    def form_valid(self, form):
        book = form.save(commit=False)
        book.save()
        form.save_m2m()
        messages.success(self.request, f"Книга '{book.title}' успешно создана.")
        return super().form_valid(form)

@method_decorator(permission_required('catalog.delete_book'), name='dispatch')
class BookDeleteView(DeleteView):
    model = Book
    template_name = 'book_confirm_delete.html'
    success_url = reverse_lazy('book_list')

    def form_valid(self, form):
        if self.object.bookinstance_set.exists():
            return redirect('book_list')
        return super().form_valid(form)


@login_required
def add_beloved_book(request, pk):
    book = get_object_or_404(Book, pk=pk)

    if request.method == 'POST':
        if hasattr(request.user, 'beloved_book'):
            request.user.beloved_book.delete()
        BelovedBook.objects.create(user=request.user, book=book)
        messages.success(request, f"Книга '{book.title}' теперь ваша любимая.")
        return redirect('book_detail', pk=pk)
    return redirect('book_list')

locallibrary/catalog/templates/all_borrowed_books.html
{% extends "base.html" %}

{% load static %}


{% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/all_borrowed_books.css' %}">
<h1>Список взятых книг</h1>
<div class="table-container">
  <table class="borrowed-books-table">
    <thead>
      <tr>
        <th>Книга</th>
        <th>Автор</th>
        <th>Кто взял</th>
        <th>Дата возврата</th>
        <th>Статус</th>
        <th>Действия</th>
      </tr>
    </thead>
    <tbody>
      {% for book in borrowed_books %}
      <tr>
        <td>{{ book.book.title }}</td>
        <td>{{ book.book.author }}</td>
        <td>{{ book.borrower }}</td>
        <td>{{ book.due_back }}</td>
        <td>{{ book.get_status_display }}</td>
        <td>
          <a href="{% url 'renew_book_librarian' book.id %}" class="btn">Обновить</a>
        </td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="6">Нет взятых книг.</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

locallibrary/catalog/templates/author_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Удалить автора: {{ author }}</h1>

{% if author.book_set.all %}

<p>Вы не сможете удалить этого автора до тех пор, пока не будут удалены все его книги:</p>
<ul>
  {% for book in author.book_set.all %}
    <li><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{book.bookinstance_set.all.count}})</li>
  {% endfor %}
</ul>

{% else %}
<p>Вы уверены, что хотите удалить автора?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Да, удалить.">
</form>
{% endif %}

{% endblock %}

locallibrary/catalog/templates/author_delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <link rel="stylesheet" href="{% static 'css/author_delete.css' %}">
<div class="delete-page-container">
    <h1>Удаление автора</h1>
    <p>Вы уверены, что хотите удалить автора <strong>{{ author.first_name }} {{ author.last_name }}</strong>?</p>
    
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn delete-btn">Удалить</button>
        <a href="{% url 'authors' %}" class="btn cancel-btn">Отмена</a>
    </form>
</div>
{% endblock %}

locallibrary/catalog/templates/author_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <link rel="stylesheet" href="{% static 'css/author_detail.css' %}">
  <h1>{{ author.first_name }} {{ author.last_name }}</h1>

  <p><strong>Дата рождения:</strong> {{ author.date_of_birth }}</p>
  <p><strong>Дата смерти:</strong> {% if author.date_of_death %}{{ author.date_of_death }}{% else %}Все еще жив{% endif %}</p>

  <h3>Книги автора {{ author.first_name }} {{ author.last_name }}</h3>
  <ul>
    {% for book in author.book_set.all %}
      <li><a href="{% url 'book_detail' book.pk %}">{{ book.title }}</a></li>
    {% empty %}
      <p>Книги этого автора не найдены.</p>
    {% endfor %}
  </ul>
  {{ block.super }}

  {% if perms.catalog.change_author or perms.catalog.delete_author %}
  <hr>
  <ul class="sidebar-nav">
    {% if perms.catalog.change_author %}
      <li><a href="{% url 'author-update' author.id %}">Обновить автора</a></li>
    {% endif %}
    {% if not author.book_set.all and perms.catalog.delete_author %}
      <li><a href="{% url 'author-delete' author.id %}">Удалить автора</a></li>
    {% endif %}
  </ul>
  {% endif %}
{% endblock %}

locallibrary/catalog/templates/author_form.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

locallibrary/catalog/templates/author_update.html
{% extends "base.html" %}

{% block content %}
<div class="form-container">
  <h2>Обновить автора</h2>
  <form action="" method="post" class="styled-form">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    {% if form.errors %}
    <div class="form-errors">
      <p>Есть некоторые проблемы с вашим вводом:</p>
      <ul>
        {% for field, errors in form.errors.items %}
        <li><strong>{{ field }}:</strong> {{ errors|join:", " }}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}
    <div class="form-buttons">
      <input type="submit" value="Save Changes" class="btn-submit" />
      <a href="{% url 'authors' %}" class="btn-cancel">Отменить</a>
    </div>
  </form>
</div>
{% endblock %}

locallibrary/catalog/templates/authors.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Авторы{% endblock %}


{% block content %}
    <link rel="stylesheet" href="{% static 'css/authors.css' %}">
    {% if user.is_staff %}
            <ul class="sidebar-nav">
                {% if perms.catalog.add_author %}
                    <div class="centered-container">
                        <a href="{% url 'author-create' %}" class="btn2">Добавить автора</a>
                    </div>
                {% endif %}
            </ul>
        {% endif %}
    <h1>Авторы</h1>
    <p>На этой странице представлены все авторы, чьи книги доступны в нашей библиотеке.</p>

    {% if authors %}
        <ul class="author-list">
            {% for author in authors %}
                <li class="author-item">
                    <h2>{{ author.name }}</h2>
                    <p>Дата рождения: {{ author.date_of_birth }}</p>
                    <p>Дата смерти: {{ author.date_of_death }}</p>
                    <p>Описание: {{ author.bio|default:"Нет информации о биографии" }}</p>
                    <a href="{% url 'author_detail' author.pk %}">Подробнее о авторе</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Нет доступных авторов</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/book_confirm_delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/book_confirm_delete.css' %}">
<div class="delete-page-container">
    <h1>Удаление книги</h1>
    <p>Вы уверены, что хотите удалить книгу <strong>{{ object.title }}</strong>?</p>
    <p>Все связанные экземпляры книги должны быть удалены перед этим.</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn delete-btn">Удалить</button>
        <a href="{% url 'book_list' %}" class="btn cancel-btn">Отмена</a>
    </form>
</div>
{% endblock %}

locallibrary/catalog/templates/book_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/book_form.css' %}">
<div class="form-container">
    <h1>Создать книгу</h1>
    <form method="post" action="{% url 'book_create' %}">
        {% csrf_token %}
        <div class="form-group">
            <label>Название:</label>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label>Автор:</label>
            {{ form.author }}
        </div>
        <div class="form-group">
            <label>Описание:</label>
            {{ form.description }}
        </div>
        <div class="form-group">
            <label>ISBN:</label>
            {{ form.isbn }}
        </div>
        <div class="form-group">
            <label>Жанры:</label>
            {{ form.genre }}
        </div>
        <div class="button-group">
            <button type="submit" class="btn save-btn">Сохранить</button>
            <a href="{% url 'book_list' %}" class="btn cancel-btn">Отмена</a>
        </div>
    </form>
</div>
{% endblock %}

locallibrary/catalog/templates/book_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <link rel="stylesheet" href="{% static 'css/book_list.css' %}">
  {% if perms.catalog.add_book %}
    <div class="add-book-button">
      <a href="{% url 'book_create' %}" class="btn">Добавить книгу</a>
    </div>
  {% endif %}
  <h1>Список книг</h1>

  {% if book_list %}
    <ul>
      {% for book in book_list %}
        <li>
          <a href="{% url 'book_detail' book.pk %}">{{ book.title }}</a>
        </li>
      {% endfor %}
    </ul>

    {% if is_paginated %}
      <div class="pagination">
        <span class="page-links">
          {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
          {% endif %}

          <span class="page-current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
          </span>

          {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
          {% endif %}
        </span>
      </div>
    {% endif %}
  {% else %}
    <p>Нет доступных книг.</p>
  {% endif %}
{% endblock %}

locallibrary/catalog/templates/book_renew_librarian.html
{% extends "base.html" %}

{% load static %}

{% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/book_renew_librarian.css' %}">
  <h2>Продление срока выдачи: {{ book_instance.book.title }}</h2>

  <p><strong>Borrower:</strong> {{ book_instance.borrower }}</p>
  <p><strong>Дата возврата:</strong> {{ book_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Продлить</button>
  </form>
  
  <a href="{% url 'all_borrowed_books' %}">Вернуться к списку</a>
{% endblock %}

locallibrary/catalog/templates/borrow_book.html
{% extends "base.html" %}

{% block content %}
  <h1>Взять книгу</h1>
  <p>Вы собираетесь взять книгу: <strong>{{ book_instance.book.title }}</strong>.</p>
  
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Подтвердить</button>
  </form>
{% endblock %}

locallibrary/catalog/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">


<div class="container">
    <h2>Динамический контент</h2>
    <p>В библиотеке имеется следующее количество записей:</p>
    <ul>
        <li><strong>Книги:</strong> {{ num_books }}</li>
        <li><strong>Копии:</strong> {{ num_instances }}</li>
        <li><strong>Доступны копии:</strong> {{ num_instances_available }}</li>
        <li><strong>Авторы:</strong> {{ num_authors }}</li>
    </ul>
    <p>Вы посетили эту страницу {{ num_visits }} раз{{ num_visits|pluralize:",а,ов" }}.</p>
</div>

<div class="search-container">
    <h3>Поиск книг по слову</h3>
    <form method="get" action="">
        <input type="text" name="q" placeholder="Введите слово" value="{{ search_word }}">
        <button type="submit">Искать</button>
    </form>

    {% if search_word %}
        <div class="search-results">
            <h3>Результаты для слова: "{{ search_word }}"</h3>
            <p><strong>Количество книг, содержащих "{{ search_word }}":</strong> {{ num_books_with_word }}</p>
            <p><strong>Количество жанров, связанных с этими книгами:</strong> {{ num_genres_with_books }}</p>
        </div>
    {% endif %}
</div>
{% endblock %}

locallibrary/catalog/templates/my_borrowed.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/my_borrowed.css' %}">
<div class="borrowed-container">
    <h2>Мои взятые книги</h2>

    {% if borrowed_books %}
    <ul class="borrowed-books-list">
        {% for instance in borrowed_books %}
        <li class="book-item">
            <div class="book-info">
                <h3>{{ instance.book.title }}</h3>
                <p><strong>Автор:</strong> {{ instance.book.author.name }}</p>
                <p><strong>Дата взятия:</strong> {{ instance.date_borrowed|date:"d M Y" }}</p>
                <p><strong>Дата возврата:</strong> {{ instance.due_back|date:"d M Y" }}</p>
            </div>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>У вас нет взятых книг.</p>
    {% endif %}
</div>
{% endblock %}